# Site settings
title: Web Slinger - Michael Bowman
email: bowmanmc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Michael Bowman - Dayton, Ohio.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://webslinger.io"
twitter_username: webslingerm
github_username:  bowmanmc

# Build settings
markdown: kramdown

exclude:
    - 'bower.json'
