# Site settings
title: Web Slinger - Michael Bowman
email: bowmanmc@gmail.com
description: Web Slinger - Michael Bowman - Dayton, Ohio
baseurl: ""
keywords: "Web Design, Web Development, Cartography, Maps, Web Slinger, Michael Bowman, Dayton, Ohio"
url: "http://webslinger.io"
twitter_username: webslingerm
github_username:  bowmanmc

# Build settings
markdown: kramdown

exclude:
    - 'bower.json'
